// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmejplnwnajjaxsqzmwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZWpwbG53bmFqamF4c3F6bXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjY4MjEsImV4cCI6MjA2NTQ0MjgyMX0.5e03IisJueMCZZBPDlRNkBntrVj3AeSfG4o2Gl6-Aow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);